# Generated by Django 4.2.4 on 2025-02-12 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='countries',
        ),
        migrations.AddField(
            model_name='country',
            name='userVisited',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visited_countries', to='users.user'),
        ),
        migrations.AddField(
            model_name='country',
            name='userWish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_countries', to='users.user'),
        ),
    ]
