# Generated by Django 4.2.4 on 2025-02-12 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_countries_country_uservisited_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='countriesVisited',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='countriesWishlist',
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
